export const GET_ALL = 'GET_ALL'; 
export const SEARCH_POKE = 'SEARCH_POKE';
export const GET_TYPES = 'GET_TYPES'; 
export const ADD_POKEMON = 'ADD_POKEMON';
export const TYPE_FILTER = 'TYPE_FILTER'; 
export const ORIGIN_FILTER = 'ORIGIN_FILTER'; 
export const ATTACK_FILTER = 'ATTACK_FILTER'; 
export const ORDER = 'ORDER'; 
export const DELETE_POKE = 'DELETE_POKE'; //new